# encoding=utf-8


PrefectureData = [
                  {'capital': '札幌市', 'is_od': True, 'name': '北海道', 'id': 1, 'population': 5460000},
                  {'capital': '青森市', 'is_od': False, 'name': '青森県', 'id': 2, 'population': 1350000},
                  {'capital': '盛岡市', 'is_od': False, 'name': '岩手県', 'id': 3, 'population': 1303000},
                  {'capital': '仙台市', 'is_od': True, 'name': '宮城県', 'id': 4, 'population': 2325000},
                  {'capital': '秋田市', 'is_od': False, 'name': '秋田県', 'id': 5, 'population': 1063000},
                  {'capital': '山形市', 'is_od': False, 'name': '山形県', 'id': 6, 'population': 1152000},
                  {'capital': '福島市', 'is_od': False, 'name': '福島県', 'id': 7, 'population': 1962000},
                  {'capital': '水戸市', 'is_od': False, 'name': '茨城県', 'id': 8, 'population': 2943000},
                  {'capital': '宇都宮市', 'is_od': False, 'name': '栃木県', 'id': 9, 'population': 1992000},
                  {'capital': '前橋市', 'is_od': False, 'name': '群馬県', 'id': 10, 'population': 1992000},
                  {'capital': 'さいたま市', 'is_od': True, 'name': '埼玉県', 'id': 11, 'population': 7212000},
                  {'capital': '千葉市', 'is_od': True, 'name': '千葉県', 'id': 12, 'population': 6195000},
                  {'capital': '新宿区', 'is_od': True, 'name': '東京都', 'id': 13, 'population': 13230000},
                  {'capital': '横浜市', 'is_od': True, 'name': '神奈川県', 'id': 14, 'population': 9067000},
                  {'capital': '新潟市', 'is_od': True, 'name': '新潟県', 'id': 15, 'population': 2347000},
                  {'capital': '富山市', 'is_od': False, 'name': '富山県', 'id': 16, 'population': 1082000},
                  {'capital': '金沢市', 'is_od': False, 'name': '石川県', 'id': 17, 'population': 1163000},
                  {'capital': '福井市', 'is_od': False, 'name': '福井県', 'id': 18, 'population': 799000},
                  {'capital': '甲府市', 'is_od': False, 'name': '山梨県', 'id': 19, 'population': 852000},
                  {'capital': '長野市', 'is_od': False, 'name': '長野県', 'id': 20, 'population': 2132000},
                  {'capital': '岐阜市', 'is_od': False, 'name': '岐阜県', 'id': 21, 'population': 2061000},
                  {'capital': '静岡市', 'is_od': True, 'name': '静岡県', 'id': 22, 'population': 3735000},
                  {'capital': '名古屋市', 'is_od': True, 'name': '愛知県', 'id': 23, 'population': 7427000},
                  {'capital': '津市', 'is_od': False, 'name': '三重県', 'id': 24, 'population': 1840000},
                  {'capital': '大津市', 'is_od': False, 'name': '滋賀県', 'id': 25, 'population': 1415000},
                  {'capital': '京都市', 'is_od': True, 'name': '京都府', 'id': 26, 'population': 2625000},
                  {'capital': '大阪市', 'is_od': True, 'name': '大阪府', 'id': 27, 'population': 8856000},
                  {'capital': '神戸市', 'is_od': True, 'name': '兵庫県', 'id': 28, 'population': 5571000},
                  {'capital': '奈良市', 'is_od': False, 'name': '奈良県', 'id': 29, 'population': 1390000},
                  {'capital': '和歌山市', 'is_od': False, 'name': '和歌山県', 'id': 30, 'population': 988000},
                  {'capital': '鳥取市', 'is_od': False, 'name': '鳥取県', 'id': 31, 'population': 582000},
                  {'capital': '松江市', 'is_od': False, 'name': '島根県', 'id': 32, 'population': 707000},
                  {'capital': '岡山市', 'is_od': True, 'name': '岡山県', 'id': 33, 'population': 1936000},
                  {'capital': '広島市', 'is_od': True, 'name': '広島県', 'id': 34, 'population': 2848000},
                  {'capital': '山口市', 'is_od': False, 'name': '山口県', 'id': 35, 'population': 1431000},
                  {'capital': '徳島市', 'is_od': False, 'name': '徳島県', 'id': 36, 'population': 776000},
                  {'capital': '高松市', 'is_od': False, 'name': '香川県', 'id': 37, 'population': 989000},
                  {'capital': '松山市', 'is_od': False, 'name': '愛媛県', 'id': 38, 'population': 1415000},
                  {'capital': '高知市', 'is_od': False, 'name': '高知県', 'id': 39, 'population': 752000},
                  {'capital': '福岡市', 'is_od': True, 'name': '福岡県', 'id': 40, 'population': 5085000},
                  {'capital': '佐賀市', 'is_od': False, 'name': '佐賀県', 'id': 41, 'population': 843000},
                  {'capital': '長崎市', 'is_od': False, 'name': '長崎県', 'id': 42, 'population': 1408000},
                  {'capital': '熊本市', 'is_od': True, 'name': '熊本県', 'id': 43, 'population': 1807000},
                  {'capital': '大分市', 'is_od': False, 'name': '大分県', 'id': 44, 'population': 1185000},
                  {'capital': '宮崎市', 'is_od': False, 'name': '宮崎県', 'id': 45, 'population': 1126000},
                  {'capital': '鹿児島市', 'is_od': False, 'name': '鹿児島県', 'id': 46, 'population': 1690000},
                  {'capital': '那覇市', 'is_od': False, 'name': '沖縄県', 'id': 47, 'population': 1409000}
                  ]

